# Use a Node.js Docker image
image: node:18

.standard-rules:
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"
      when: always

# Define stages
stages:
  - install
  - build
  - test

# Install dependencies
install_dependencies:
  stage: install
  extends: .standard-rules
  script:
    - echo "Installing dependencies..."
    - npm ci
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 day

# Build the project
build_project:
  stage: build
  extends: .standard-rules
  script:
    - echo "Building the project..."
    - npm run build
  dependencies:
    - install_dependencies
  artifacts:
    paths:
      - dist/
    expire_in: 1 day

# Run tests
run_tests:
  stage: test
  extends: .standard-rules
  script:
    - echo "Running tests..."
    - npm run test
    - npm run test:e2e # Add this if you have e2e tests
  dependencies:
    - install_dependencies

# Optional: Linting stage
lint_code:
  extends: .standard-rules
  stage: test
  script:
    - echo "Running lint..."
    - npm run lint
  allow_failure: true
  dependencies:
    - install_dependencies